import Link from 'next/link'
import NewArticleForm from '../pages/newArticleForm';
import Layout from '../components/Layout.js'
import { createClient } from '@supabase/supabase-js';
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

export default function Articles({ articles }) {
  return (
    <Layout title="Articles" description="Generated by create next app">
      <div className="create-article-button">
        <Link href="/newArticleForm">New Article</Link>
      </div>
      <h1 className='wt-title'>Web technologies articles</h1>
      <p className="italic font-bold my-5">Here are all the articles</p>
      <ul>
        {articles.map(article => (
          <li key={article.id} className="my-5">
            <h2 className="font-bold mb-1">
              <Link href={`/articles/${article.id}`}>
                {article.title || ' '} {/* replace null by a blank */}
              </Link>
            </h2>
            <p className="article-info">
              {(article.author ? `Written by ${article.author.firstname} ${article.author.lastname}` : ' ')}
              {article.created_at ? ` - ${new Date(article.created_at).toLocaleDateString()}` : ' '}
            </p>
            {article.content ? <p className="article-content">{article.content}</p> : ' '}
          </li>
        ))}
      </ul>
    </Layout>
  )
}




export async function getStaticProps() {
  let articles = [];
  const { data, error } = await supabase
    .from('articles')
    .select(`
      *,
      author:contacts (
        firstname,
        lastname
      )
    `);
  if (!error && data) {
    console.log('Articles data:', data); 
    articles = data;
  } else {
    console.error('Error fetching articles:', error);
  }

  return {
    props: {
      articles: articles
    }
  }
}