import React, { useEffect, useState, useContext } from 'react';
import Link from 'next/link';
import Layout from '../components/Layout.js';
import UserContext from '../components/UserContext';
import AuthForm from "@/pages/auth-form";
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

export default function Page() {
   
    return (
        <Layout title="HomePage" description="Generated by create next app">
            <h1>Welcome to Ferrari News website</h1>
            <p>This is the home page</p>
        </Layout>
    );
}
