import React, { useEffect, useState, useContext } from 'react';
import Link from 'next/link';
import Layout from '../components/Layout.js';
import UserContext from '../components/UserContext';
import AuthForm from "@/pages/auth-form";
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

export default function Page() {
    const { profile } = useContext(UserContext);
    const [articles, setArticles] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {

        async function fetchData() {
            const { data, error } = await supabase
                .from('articles')
                .select('*');
            if (!error && data) {
                setArticles(data);
                console.log('data')
                console.log(supabase.from('articles').select('*'));
            } else {
                console.error('Error fetching data: ', error);
            }
            setLoading(false);
        }

        fetchData().then(r => console.log(r));
    }, []);

    if (loading) {
        return <div>Loading...</div>;
    }

    return (
        <Layout title="" description="Generated by create next app">
            {profile && (
                <div>
                    {profile.username},
                </div>
            )}
            {articles.length > 0 ? (
                <h1 className='wt-title'>
                    {articles[0].title}
                </h1>
            ) : (
                <h1 className='wt-title'>No articles found</h1>
            )}

            {/* Reste du code ... */}
        </Layout>
    );
}
