import Link from 'next/link';
import Layout from '../../components/Layout.js';
import { useRouter } from 'next/router'; 
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

export default function ArticlePage({ article, comments}) {
  const router = useRouter();

  // function to delete an article
  const handleDelete = async () => {
    if (window.confirm('Are you sure you want to delete this article?')) {
      const { error } = await supabase
        .from('articles')
        .delete()
        .match({ id: article.id });
  
      if (error) {
        console.error('Error deleting article:', error);
      } else {
        router.push('/articles'); // go back to the articles page after deleting
      }
    }
  };

  const handleEdit = () => {
    router.push(`/edit-article/${article.id}`); 
  };
  

  return (
    <Layout
    
      title={article.title || ' '}
      description="Generated by create next app"
    >
      <div className="in-main">
        <div className="back-to-articles">
          <Link href="/articles">← Back</Link>
        </div>
        <div className="">
          <h1 className='wt-title'>{article.title || ' '}</h1>
          <p className="article-info2">
            {article.author ? `Written by ${article.author.firstname} ${article.author.lastname}` : ' '}
            {article.created_at ? ` - ${new Date(article.created_at).toLocaleDateString()}` : ' '}
          </p>
          {article.image_url && (
            <img src={article.image_url} alt={article.title} className="article-image" />
          )}
          <div className="div-article-content">
            <div className="article-content">
              {article.message || ' '} {/* replace null by a blank if there is no content */}
            </div>
          </div>
        </div>
        <div className="div-class-edit">
          <button onClick={handleEdit} className="edit-article-button">
            ✍ Edit
          </button>
          <button onClick={handleDelete} className="delete-article-button">
            ✖ Supprimer
          </button>
        </div>
        <div className="comment-section">
          <h2 className="comment-name-section">Comments ({comments.length}):</h2>
          {comments.map(comment => (
            <div key={comment.id} className="comment">
              <p className="comment-author">Author: {comment.author ? `${comment.author.firstname} ${comment.author.lastname}` : 'Unknown'}</p>
              <p className="comment-message">{comment.message}</p>
            </div>
          ))}
        </div>
      </div>
    </Layout>
  )
}


export async function getStaticProps(ctx) {
  const { id } = ctx.params;
  // Fetch article
  const { data: article, error: articleError } = await supabase
    .from('articles')
    .select(`
      *,
      author:contacts (
        firstname,
        lastname
      )
    `)
    .eq('id', id)
    .single();

  // Fetch comments for the article
  const { data: comments, error: commentsError } = await supabase
    .from('comments')
    .select(`
      id,
      message,
      created_at,
      author:contacts (
        firstname,
        lastname
      )
    `)
    .eq('article', id);

  if (articleError) {
    console.error('Error fetching article:', articleError);
  }

  if (commentsError) {
    console.error('Error fetching comments:', commentsError);

  }

  return {
    props: {
      article: article || {},
      comments: comments || []
    }
  };
}





export async function getStaticPaths() {
  const { data: articles, error } = await supabase
    .from('articles')
    .select('id');

  if (error || !articles) {
    console.error('Error fetching articles:', error);
    return { paths: [], fallback: false };
  }

  return {
    paths: articles.map(article => ({ params: { id: article.id.toString() } })),
    fallback: false
  };
}
